#!/usr/bin/env tsx
/**
 * Downloads country flag SVGs from flagcdn.com and saves them to public/flags/{isoA3}.svg.
 * Reads iso2 codes from public/data/countries.json (generated by process-geodata.ts).
 *
 * Usage:  npm run fetch-flags
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs'

const DATA_PATH = 'public/data/countries.json'
const FLAGS_DIR = 'public/flags'
const CDN_BASE = 'https://flagcdn.com'

interface CountryNode {
  isoA3: string
  iso2?: string
}

async function main() {
  mkdirSync(FLAGS_DIR, { recursive: true })

  const { nodes } = JSON.parse(readFileSync(DATA_PATH, 'utf8')) as { nodes: CountryNode[] }

  // Collect unique isoA3 → iso2 pairs (multiple polygons share the same country flag)
  const countries = new Map<string, string>() // isoA3 → iso2
  for (const n of nodes) {
    if (n.iso2 && !countries.has(n.isoA3)) {
      countries.set(n.isoA3, n.iso2)
    }
  }

  console.log(`Downloading ${countries.size} flags from flagcdn.com…`)
  let ok = 0
  let fail = 0

  for (const [isoA3, iso2] of countries) {
    const candidates = [iso2]
    // Fallback for subdivision codes like "cn-tw" → try "tw"
    if (iso2.includes('-')) candidates.push(iso2.split('-').pop()!)

    const dest = `${FLAGS_DIR}/${isoA3}.svg`
    let succeeded = false

    for (const code of candidates) {
      const url = `${CDN_BASE}/${code}.svg`
      try {
        const r = await fetch(url)
        if (!r.ok) continue
        const svg = await r.text()
        writeFileSync(dest, svg, 'utf8')
        ok++
        process.stdout.write(`\r  ${ok + fail}/${countries.size}  ${isoA3} (${code})        `)
        succeeded = true
        break
      } catch {
        // try next candidate
      }
    }

    if (!succeeded) {
      console.warn(`\n  WARN: ${isoA3} (${iso2}): all candidates failed`)
      fail++
    }
  }

  console.log(`\nDone: ${ok} downloaded, ${fail} failed`)
}

main().catch(e => { console.error(e); process.exit(1) })
